util: fix print statements
Compiling with OpenWrt x86_64 gives following errors:

util.c:59:13: error: format '%lu' expects argument of type 'long
unsigned int', but argument 3 has type 'rlim_t' {aka 'long long unsigned
int'} [-Werror=format=]
    pr_debug("Current rlimit %lu already >= minimum %u\n",
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      limit.rlim_cur, min_limit);
      ~~~~~~~~~~~~~~

util.c:66:12: error: format '%lu' expects argument of type 'long
unsigned int', but argument 3 has type 'rlim_t' {aka 'long long unsigned
int'} [-Werror=format=]
   pr_debug("Doubling current rlimit of %lu\n", limit.rlim_cur);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~
Since rlim_t is just an unsigned integer type we can cast to uintmax_t.
uintmax_t is the maximum-width unsigned integer type.

To print uintmax_t we change %lu to %ju.

Signed-off-by: Nick Hainke <vincent@systemli.org>