libxdp/xsk: Don't make assumptions about the buffer size of ifname
Add suggestions from @tohojo for usage of strncpy instead of memcpy
Update xdpsock.c, fix build with "-Werror=stringop-overread"
Also remove the "\0" set, already done via safe_strncpy

Happening on Ubuntu 26.04

/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:10: error: ‘__builtin_memcpy’ reading 15 bytes from a region of size 3 [-Werror=stringop-overread]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ^
lto1: all warnings being treated as errors
make[4]: *** [/tmp/ccVkV0Po.mk:2: /tmp/ccgGP0u2.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/x86_64-linux-gnu-ld.bfd: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[3]: *** [../common.mk:107: test-tool] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/lib/testing'
make[2]: *** [Makefile:16: testing] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/lib'
make[1]: *** [Makefile:31: lib] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: error: make -j4 returned exit code 2
make: *** [debian/rules:26: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

Signed-off-by: Gianfranco Costamagna <locutusofborg@debian.org>