use struct ethhdr (linux) to enhance portability (clang)
building with clang fails with:
/usr/include/netinet/if_ether.h:115:8: error: redefinition of 'ethhdr'

use `struct ethhdr` (linux) instead of `struct ether_header` (glibc) and
remove net/netinet-headers to avoid redefinition of `ethhdr`

fixes: #570
Signed-off-by: Pepper Gray <hello@peppergray.xyz>